### ISSUE TITLE
HTTP request failed

### ISSUE THREAD

**Issue by gdolenc** [coderjoe/gogeocode#5]
It is not working for me. I get an error: 

Warning: file_get_contents(http://maps.google.com/maps/geo?q=1+Lomb+Memorial+Drive+Rochester+NY%2C+14623&output=xml&oe=UTF-8&key=xxx): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden in C:\xxx\BaseGeocode.php on line 86 Call Stack: 0.0004 359608 

What could be the problem?

**Comment by coderjoe** [comment]
A year with no pull request. Closing as abandoned.
